---
After:
  - '#corefieldtypes'
---
SilverStripe\Core\Injector\Injector:
  Dcentrica\Registration\Security\Security:
    properties:
      Authenticators:
        default: '%$Dcentrica\Registration\Security\MemberAuthenticator'
---
After:
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'Security//$Action/$ID/$OtherID': Dcentrica\Registration\Security\Security