---
Name: silverstripe-registration
After:
  - '#corefieldtypes'
Only:
  envvarset: REGISTRATION_ENABLED
---
SilverStripe\Core\Injector\Injector:
  Dcentrica\Registration\Security\Security:
    properties:
      Authenticators:
        default: '%$Dcentrica\Registration\Security\MemberAuthenticator'

Dcentrica\Registration\Security\RegisterHandler:
  # Do we want Silverstripe to auto-login post registration?
  login_after_register: true

---
After:
  - '#coreroutes'
Only:
  envvarset: REGISTRATION_ENABLED
---
SilverStripe\Control\Director:
  rules:
    'Security//$Action/$ID/$OtherID': Dcentrica\Registration\Security\Security