---
After:
  - '#corefieldtypes'
---
SilverStripe\Core\Injector\Injector:
  Registration\Security\Security:
    properties:
      Authenticators:
        default: '%$Registration\Security\MemberAuthenticator\MemberAuthenticator'
---
After:
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'Security//$Action/$ID/$OtherID': Registration\Security\Security
---
After:
  - '#corepasswords'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\PasswordValidator:
    properties:
      MinLength: 8
      HistoricCount: 0

# In the case someone uses `new PasswordValidator` instead of Injector, provide some safe defaults through config.
SilverStripe\Security\PasswordValidator:
  min_length: 8
  historic_count: 0