---
Name: silverstripe-registration-config
After:
  - '#corefieldtypes'
Only:
  envvarset: REGISTRATION_ENABLED
---

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: '%$Dcentrica\Registration\Security\RegistrationAuthenticator'

Dcentrica\Registration\Security\RegistrationHandler:
  # Do we want Silverstripe to auto-login post registration?
  login_after_register: true